### ISSUE TITLE
better exception handling when in clipboard is not text

### ISSUE THREAD

**Issue by jiri-one** [jiri-one/easydict-gtk#1]
`Traceback (most recent call last):
  File "/home/jiri/Workspace/EasyDict/easydict_gtk/easydict/src/handlers.py", line 52, in onClipboard
    if len(self.clipboard.wait_for_text().split()) == 1: # third condition is check, if in clipboard is just one word
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/jiri/Workspace/EasyDict/easydict_gtk/easydict/src/handlers.py", line 52, in onClipboard
    if len(self.clipboard.wait_for_text().split()) == 1: # third condition is check, if in clipboard is just one word
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by jiri-one** [comment]
Now it is fixed.
